inputs:


versionSpec: '$(python.version)'


displayName: 'Use Python $(python.version)'


- script: python "sum.py"



- task: PythonScript@0


inputs:


scriptSource: 'inline'


script: |


print('Hello world 1')


print('Hello world 2')